### ISSUE TITLE
Program: Pathway vs Credits

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#108]
Is it possible to have the "Educational Unit Type"  part show up only if you select "Credits/CEUs"; selected "Learning Pathway" and looked like I still needed to pick a unit type. But then the unit type isn't even there after you create the program as a Pathway 

<img width="1438" alt="Screen Shot 2023-03-30 at 1 39 20 PM" src="https://user-images.githubusercontent.com/129342490/229244737-bbfc6811-35f2-4fd1-b032-9f9b687a2e84.png">

<img width="1438" alt="Screen Shot 2023-03-30 at 1 40 21 PM" src="https://user-images.githubusercontent.com/129342490/229244748-0966d6dc-49ff-4dfd-914b-755b9826b672.png">

**Comment by josh-havens** [comment]
We need to hide the Educational Units Type selection and put a select listener on the radio component to show that panel if Credits/CEUs is selected (hide if Learning Pathway is selected).
We should also (only temporarily) remove Learning Pathway as an option in the radio component because that function isn't ready yet.

**Comment by SAStevens1** [comment]
Added new Click Listener on radio button to hide EUT when Learning Pathway is selected. Then I removed Learning Pathway as an option for now.

NOTE: I added a comment with importance in the History so we can revert back to Learning Pathway when it is ready to be displayed.
