### ISSUE TITLE
Odd spacing of Draft Programs

### ISSUE THREAD

**Issue by AyappaA** [GlobalUniversity/ArkTrainingNetwork#113]
The way these programs are listed at the end of the list just looks odd, perhaps if some kind of equal spacing boundaries could be in place? I'd imagine the length of a program description and size of font is contributing to the difference in sizes of the preview box

<img width="1436" alt="Screen Shot 2023-04-03 at 6 58 58 PM" src="https://user-images.githubusercontent.com/129342490/229653252-ace6d7a2-3b83-43c1-bb8c-5a087967e114.png">

**Comment by kdegarmo** [comment]
@AyappaA Yes, this is kind of related to Josh's comment on another bug, I think they're waiting on some feedback before making additional changes to Programs. There's no max-height or character count or anything on these descriptions at the present moment so that's why the spacing gets weird with longer descriptions.

**Comment by kdegarmo** [comment]
Set max height on the card and overflow-y for text as hidden so all of these should be max height 200px. Text is just set to cut off but hopefully the program descriptions aren't terribly long. Time will tell but this is good for now.
