### ISSUE TITLE
Creating a course module

### ISSUE THREAD

**Issue by MrBonham** [GlobalUniversity/ArkTrainingNetwork#16]
Creating a course a Module with a Question it is not saving all the options I am putting. I hit Save and the the boxes flys at the bottom but it does not save the Value in the Answers box. 
![image](https://user-images.githubusercontent.com/128522455/228043410-2641796a-fe09-4323-a220-b001b41e8d9f.png)

**Comment by ChrisLamberth** [comment]
I'm not happy with the fix, but I've put too much time into this. Basically, when you added an option (Sub_ModuleQuestion_Option), the Current_Module data pathway through the CCs didn't have the data. I tried EVERYTHING in the way of adding the object to the screen and/or variable to allow the list item to take text input (so that the save button would save it). 
The fix was just to reload the module on the screen via the module type SwitchCase VLC
