### ISSUE TITLE
Profile Information > save works, but doesn’t have a confirmation

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#165]
Student > Profile Information > save works, but doesn’t have a confirmation

**Comment by kdegarmo** [comment]
You might check this again and re-open if you're getting the same issue. I updated a couple of my user profiles this morning and the little toast notification comes up in the bottom right of the screen that indicates "Profile Saved" so if this was some sort of bug, it may have been fixed in the last push to test/prod.
