### ISSUE TITLE
Home Page > Account Creation Modal > There are no fields. 

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#182]
Home Page > Account Creation Modal > There are no fields. This renders new account creation impossible.

<img width="452" alt="Screen Shot 2023-07-05 at 10 32 56 AM" src="https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/22bd060d-35cb-4b88-a2b6-ef9a667adb6c">

**Comment by SAStevens1** [comment]
After looking into this it was determined as a "user error" on the Branch side as an Administrator didn't set a default form. When adding the setting on a Branch we might need to make sure they have a form that can be default otherwise they can't set it that way? Anyway, user error on the Branch Administrator's part.
