### ISSUE TITLE
Administrator > Assigned User Tags are incongruent in View Profile vs. Administrator Settings

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#223]
Assigned User Tags are incongruent in View Profile vs. Administrator Settings

![Screen Shot 2023-07-07 at 11 32 17 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/0cbfab71-fc05-47a3-863d-1ac38468d555)

![Screen Shot 2023-07-07 at 11 32 07 AM](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129097082/70eeaa2c-7b3e-45d5-90f3-3b4e2e2b5762)

**Comment by kdegarmo** [comment]
I'm not exactly sure what specifically you were referring to here since no user tags were assigned in the one screenshot. But I guess I haven't really done much of anything with user tags stuff since it was finished so I came in and cleaned up the UI so I think this is okay now. Columns should be aligned, unnecessary hovers removed, etc. Re-open with new info if this isn't what you were referring to.
