### ISSUE TITLE
Programs: Archived Forms

### ISSUE THREAD

**Issue by skruegergu** [GlobalUniversity/ArkTrainingNetwork#53]
Why is there a plus button here? I’m not creating an archived form.
![Programs](https://user-images.githubusercontent.com/129097082/228367712-68efaea7-3b5c-4a36-acf9-f84956a136a2.png)

**Comment by SAStevens1** [comment]
Based on Josh's comment I will explain this from the standpoint of the Course Manager since Program Manager will be redeisgned to reflect it.

When you navigate to Course Manager it defaults to Active courses and next to the search bar is the add course button. However the way we have designed the UX of Course Builder, everytime you create a new course it defaults to Draft until you set it as active or schedule it to switch. If we follow the same logic mentioned in this bug, Active Courses having the add button would also be considered a problem. Archived has the add button, but if you are someone with the permission to create courses (or programs in this case) I believe our UX is consistent in that you will know the course(program) you are creating is a Draft, just as it would be if you clicked it in Active Courses. Less clicks this way. So, I will make a seperate bug for Josh's comment, as for the original bug, I will relabel this as a question/ observation and it will not be fixed if we are to be consistent with the way Program Manager will be redesigned to match the Course Manager
![image](https://github.com/GlobalUniversity/ArkTrainingNetwork/assets/129208341/27754e6c-586f-49bd-8507-42158734bb38)
